# Recall

# Regression

In [3]:
x=[1,2,3,4,5,6,7,8,9,10]
y=[2,4,6,8,10,12,14,16,18,20]
# y = 2x

In [5]:
from sklearn.linear_model import LinearRegression

In [6]:
import numpy as np

In [7]:
x

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
x=np.array(x).reshape(-1,1) # satirlari sutun yapar

In [9]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [10]:
lr=LinearRegression()

In [11]:
lr.fit(x,y)

LinearRegression()

In [15]:
m=lr.coef_

In [16]:
b=lr.intercept_

In [17]:
m*60+b

array([120.])

In [18]:
lr.predict([[60]])

array([120.])

In [19]:
import pandas as pd

In [26]:
data={'Age':[25,30,35,40,None],
      'Gender':['Male','Female','Male','Female','Female'],
      'Salary':[50000,60000,70000,None,90000]
     }

In [27]:
data

{'Age': [25, 30, 35, 40, None],
 'Gender': ['Male', 'Female', 'Male', 'Female', 'Female'],
 'Salary': [50000, 60000, 70000, None, 90000]}

In [28]:
df=pd.DataFrame(data)

In [29]:
df

    Age  Gender   Salary
0  25.0    Male  50000.0
1  30.0  Female  60000.0
2  35.0    Male  70000.0
3  40.0  Female      NaN
4   NaN  Female  90000.0

In [30]:
df['Age']=df['Age'].fillna(df.Age.mean())

In [31]:
df['Salary']=df['Salary'].fillna(df.Salary.mode()[0])

In [32]:
x=df[['Age','Gender']]
y=df[['Salary']]

In [33]:
x=pd.get_dummies(x,drop_first=True)

In [34]:
x

    Age  Gender_Male
0  25.0         True
1  30.0        False
2  35.0         True
3  40.0        False
4  32.5        False

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc=StandardScaler()

In [50]:
x=sc.fit_transform(x)

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=42)

In [53]:
from sklearn.tree import DecisionTreeRegressor

In [54]:
dt=DecisionTreeRegressor()

In [55]:
model=dt.fit(x_train,y_train)

In [45]:
tahmin=model.predict(x_test)

In [56]:
tahmin=model.predict(x) # verimiz fazla olmadigi icin direkt x verelim

In [46]:
from sklearn.metrics import r2_score

In [47]:
r2_score(y_test,tahmin)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_regression.py:1266: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)

nan

In [57]:
r2_score(y,tahmin) # verimiz fazla olmadigi icin direkt y verelim

0.1964285714285714

In [58]:
yd=[[57,True]]

In [59]:
model.predict(yd)

array([50000.])

# Classification

In [61]:
data={'Age':[25,30,35,40,53,32,45,22,47,55],
      'Gender':['Male','Female','Male','Female','Female','Male','Female','Male','Female','Female'],
      'Salary':[5000,60000,70000,23000,90000,50000,60000,72000,65000,90000],
      'Purchased':[0,0,1,1,1,1,1,0,0,1]
     }

In [62]:
df=pd.DataFrame(data)

In [63]:
df

   Age  Gender  Salary  Purchased
0   25    Male    5000          0
1   30  Female   60000          0
2   35    Male   70000          1
3   40  Female   23000          1
4   53  Female   90000          1
5   32    Male   50000          1
6   45  Female   60000          1
7   22    Male   72000          0
8   47  Female   65000          0
9   55  Female   90000          1

In [64]:
from sklearn.tree import DecisionTreeClassifier

In [65]:
dc=DecisionTreeClassifier()

In [67]:
x=df[['Age','Gender','Salary']]
y=df[['Purchased']]

In [68]:
x=pd.get_dummies(x,drop_first=True)

In [71]:
x

   Age  Salary  Gender_Male
0   25    5000         True
1   30   60000        False
2   35   70000         True
3   40   23000        False
4   53   90000        False
5   32   50000         True
6   45   60000        False
7   22   72000         True
8   47   65000        False
9   55   90000        False

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=42)

In [73]:
model=dc.fit(x_train,y_train)

In [74]:
tahmin=model.predict(x_test)

In [75]:
from sklearn.metrics import accuracy_score

In [77]:
accuracy_score(y_test,tahmin) # veri cok az oldugu icin 0 cikti

0.0

In [79]:
model.predict([[40,True,60000]])[0]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

np.int64(1)

In [80]:
# True geldigi icin alisveris yapacak