# Tavsiye(Oneri) Sitemleri: Film Tavsiyesi

In [2]:
import pandas as pd

In [12]:
ratings=pd.read_csv('spark/ml-100k/u.data', sep='\t', header=None, names=['user_id','movie_id','rating'],usecols=range(3))

In [13]:
ratings

        user_id  movie_id  rating
0             0        50       5
1             0       172       5
2             0       133       1
3           196       242       3
4           186       302       3
...         ...       ...     ...
99998       880       476       3
99999       716       204       5
100000      276      1090       1
100001       13       225       2
100002       12       203       3

[100003 rows x 3 columns]

In [14]:
movies=pd.read_csv('spark/ml-100k/u.item', encoding='iso-8859-1', sep='|', header=None, names=['movie_id','title'],usecols=range(2))

In [15]:
movies

      movie_id                                      title
0            1                           Toy Story (1995)
1            2                           GoldenEye (1995)
2            3                          Four Rooms (1995)
3            4                          Get Shorty (1995)
4            5                             Copycat (1995)
...        ...                                        ...
1677      1678                          Mat' i syn (1997)
1678      1679                           B. Monkey (1998)
1679      1680                       Sliding Doors (1998)
1680      1681                        You So Crazy (1994)
1681      1682  Scream of Stone (Schrei aus Stein) (1991)

[1682 rows x 2 columns]

In [16]:
user=pd.read_csv('spark/ml-100k/u.user', sep='|', header=None, names=['user_id','age','gender','profession','zipcode'])

In [17]:
user

     user_id  age gender     profession zipcode
0          1   24      M     technician   85711
1          2   53      F          other   94043
2          3   23      M         writer   32067
3          4   24      M     technician   43537
4          5   33      F          other   15213
..       ...  ...    ...            ...     ...
938      939   26      F        student   33319
939      940   32      M  administrator   02215
940      941   20      M        student   97229
941      942   48      F      librarian   78209
942      943   22      M        student   77841

[943 rows x 5 columns]

In [18]:
rating=pd.merge(movies,ratings)

In [19]:
rating

        movie_id                                      title  user_id  rating
0              1                           Toy Story (1995)      308       4
1              1                           Toy Story (1995)      287       5
2              1                           Toy Story (1995)      148       4
3              1                           Toy Story (1995)      280       4
4              1                           Toy Story (1995)       66       3
...          ...                                        ...      ...     ...
99998       1678                          Mat' i syn (1997)      863       1
99999       1679                           B. Monkey (1998)      863       3
100000      1680                       Sliding Doors (1998)      863       2
100001      1681                        You So Crazy (1994)      896       3
100002      1682  Scream of Stone (Schrei aus Stein) (1991)      916       3

[100003 rows x 4 columns]

In [20]:
rating.title.value_counts()

title
Star Wars (1977)                        584
Contact (1997)                          509
Fargo (1996)                            508
Return of the Jedi (1983)               507
Liar Liar (1997)                        485
                                       ...
Invitation, The (Zaproszenie) (1986)      1
Symphonie pastorale, La (1946)            1
Nothing Personal (1995)                   1
Ripe (1996)                               1
Brother's Kiss, A (1997)                  1
Name: count, Length: 1664, dtype: int64

In [21]:
import numpy as np

In [22]:
mg=rating.groupby('title').agg({'rating':[np.size, np.sum, np.mean]})

C:\Users\kosey\AppData\Local\Temp\ipykernel_11892\1832300426.py:1: FutureWarning: The provided callable <function sum at 0x0000029BD753A0C0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  mg=rating.groupby('title').agg({'rating':[np.size, np.sum, np.mean]})
C:\Users\kosey\AppData\Local\Temp\ipykernel_11892\1832300426.py:1: FutureWarning: The provided callable <function mean at 0x0000029BD753B4C0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mg=rating.groupby('title').agg({'rating':[np.size, np.sum, np.mean]})

In [23]:
mg

                                      rating
                                        size  sum      mean
title
'Til There Was You (1997)                  9   21  2.333333
1-900 (1994)                               5   13  2.600000
101 Dalmatians (1996)                    109  317  2.908257
12 Angry Men (1957)                      125  543  4.344000
187 (1997)                                41  124  3.024390
...                                      ...  ...       ...
Young Guns II (1990)                      44  122  2.772727
Young Poisoner's Handbook, The (1995)     41  137  3.341463
Zeus and Roxanne (1997)                    6   13  2.166667
unknown                                    9   31  3.444444
Á köldum klaka (Cold Fever) (1994)         1    3  3.000000

[1664 rows x 3 columns]

In [25]:
pm=mg.sort_values(('rating','mean'),ascending=False)

In [26]:
pm

                                                  rating
                                                    size sum mean
title
Aiqing wansui (1994)                                   1   5  5.0
Entertaining Angels: The Dorothy Day Story (1996)      1   5  5.0
Santa with Muscles (1996)                              2  10  5.0
Prefontaine (1997)                                     3  15  5.0
They Made Me a Criminal (1939)                         1   5  5.0
...                                                  ...  ..  ...
Pharaoh's Army (1995)                                  1   1  1.0
August (1996)                                          1   1  1.0
Babyfever (1994)                                       2   2  1.0
Amityville: A New Generation (1993)                    5   5  1.0
Woman in Question, The (1950)                          1   1  1.0

[1664 rows x 3 columns]

In [27]:
gs=pm['rating']['sum'].sum()

In [28]:
gs

np.int64(352997)

In [29]:
pm['percentage']=pm['rating']['sum'].div(gs)*100

In [30]:
pm.head()

                                                  rating          percentage
                                                    size sum mean
title
Aiqing wansui (1994)                                   1   5  5.0   0.001416
Entertaining Angels: The Dorothy Day Story (1996)      1   5  5.0   0.001416
Santa with Muscles (1996)                              2  10  5.0   0.002833
Prefontaine (1997)                                     3  15  5.0   0.004249
They Made Me a Criminal (1939)                         1   5  5.0   0.001416

In [31]:
pm['rank']=pm['percentage'].rank(ascending=False)

In [32]:
pm.sort_values(by='rank',ascending=True)

                               rating                 percentage    rank
                                 size   sum      mean
title
Star Wars (1977)                  584  2546  4.359589   0.721253     1.0
Fargo (1996)                      508  2111  4.155512   0.598022     2.0
Return of the Jedi (1983)         507  2032  4.007890   0.575642     3.0
Contact (1997)                    509  1936  3.803536   0.548447     4.0
Raiders of the Lost Ark (1981)    420  1786  4.252381   0.505953     5.0
...                               ...   ...       ...        ...     ...
Very Natural Thing, A (1974)        1     1  1.000000   0.000283  1636.0
Low Life, The (1994)                1     1  1.000000   0.000283  1636.0
Lotto Land (1995)                   1     1  1.000000   0.000283  1636.0
Leopard Son, The (1996)             1     1  1.000000   0.000283  1636.0
Mat' i syn (1997)                   1     1  1.000000   0.000283  1636.0

[1664 rows x 5 columns]

Bu projede en populer filmleri bulup tavsiye ettik